version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d  # This will automatically execute any SQL scripts placed in this folder
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
      - /app/node_modules  # Prevents host from overwriting container's node_modules
    depends_on:
      - db
    networks:
      - app-network
    working_dir: /app  # Optional: if not already set in Dockerfile
    environment:
      - NODE_ENV=development

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile  # Capital D is the default, double-check your filename
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - app-network
    working_dir: /app
    environment:
      - CHOKIDAR_USEPOLLING=true  # Enables hot reload in React/Vite/etc.
      - NODE_ENV=development

networks:
  app-network:
    driver: bridge
